import { Kufam } from "next/font/google";
import "./globals.css";
import "@/i18n";
import App from "./App";

const kufam = Kufam({
  variable: "--font-kufam",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Asfar Tiba",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kufam.variable}`}>
        <App> {children}</App>
      </body>
    </html>
  );
}
